name: ird
channels:
  - conda-forge
dependencies:
  - python
  - bs4
  - coverage
  - deepdiff
  - fabric
  - gitpython
  - hydra-core
  - isort
  - loguru
  - matplotlib
  - mypy
  - networkx
  - numpy
  - onnx
  - openpyxl
  - polars
  - pre-commit
  - pydantic
  - pyelftools
  - pytest-cov
  - pytest-mock
  - pytest-xdist
  - pyyaml
  - ruff
  - simpy
  - sphinx
  - sphinx-rtd-theme
  - yaml
  - pip
  - pip:
    - lxml-stubs
    - pytest
    - types-networkx
    - types-PYYAML
    - types-requests
